[project]
name = "dvn"
dynamic = ["version"]                                              # let setuptools-scm handle versioning
description = "DVN: Computer Vision for Drones"
readme = "README.md"
requires-python = "==3.11"

dependencies = [
    "ultralytics",
    "opencv-python",
    "httpx",
    "scikit-learn",
    "tqdm",
    "imageio",
    "pyrefly",
    "onnxruntime",
]

[tool.mypy]
python_version = "3.11"
strict = true

[build-system]
requires = ["setuptools", "wheel", "setuptools-scm[toml]"]
build-backend = "setuptools.build_meta"

# ⬇⬇⬇  THIS tells setuptools what to install  ⬇⬇⬇
[tool.setuptools]
package-dir = { "" = "src" } # “top‑level imports come from src/”

[tool.setuptools_scm]
fallback_version = "0.2.0"

[tool.setuptools.packages.find]
where = ["src"]         # search only there
include = ["dvn*", "sat*"] # pick up both packages

[tool.pyrefly]
python-version = "3.11.0"
